name: Deploy

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'      
      
    - name: Checkout submodules
      run: git submodule update --init --recursive



    - name: Setup Hexo & COS env
      env:
        SecretId: ${{ secrets.SecretId }}
        SecretKey: ${{ secrets.SecretKey }}

      run: |
        npm install hexo-cli -g
        npm install
        sed -i "s/SecretId/${SecretId}/" _config.yml
        sed -i "s/SecretKey/${SecretKey}/" _config.yml
    
    - name: Deploy to COS
      run: |
        hexo clean && hexo g && hexo d
